"""Initial migration: Institution and ExchangeRate models

Revision ID: 53d006478519
Revises:
Create Date: 2025-09-12 13:42:13.028076

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "53d006478519"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_institution_name", "institutions", ["name"], unique=False)
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=False),
        sa.Column("buy_rate", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "recorded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_exchange_rate_institution",
        "exchange_rates",
        ["institution_id"],
        unique=False,
    )
    op.create_index(
        "idx_exchange_rate_recorded_at", "exchange_rates", ["recorded_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_exchange_rate_recorded_at", table_name="exchange_rates")
    op.drop_index("idx_exchange_rate_institution", table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index("idx_institution_name", table_name="institutions")
    op.drop_table("institutions")
    # ### end Alembic commands ###
